### ISSUE TITLE
urlopen error timed out with proxy

### ISSUE THREAD

**Issue by shellshock1953** [PagerDuty/pdagent#112]
All done, as asked in: https://community.pagerduty.com/t/certificateerror-hostname-proxy-doesnt-match-either-of-pagerduty-com-pagerduty-com/1002/5
proxy has name internet_proxy.pagerduty.com, curl (internet_proxy.pagerduty.com:3128 http and https) worker fine. For some time all alerts were going  threw this proxy.
But
For few days, pdagent was disabled, and now, I`m trying to set it to work.

pd-queue shows Traceback AttributeError: 'int' object has no attribute 'get'.
Trying to send any alarm causes:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pdagent/sendevent.py", line 90, in send_event
    response = self._urllib2.urlopen(request)
  File "/usr/lib/python2.7/site-packages/pdagent/thirdparty/httpswithverify.py", line 153, in urlopen
    return url_opener_cache[ca_certs].open(url, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/pdagent/thirdparty/httpswithverify.py", line 136, in https_open
    return self.do_open(self._proxyHTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1200, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

```
Double checked proxy - proxy works.
What possible ways to understand what happend?

**Comment by shellshock1953** [comment]
Seem to be issues inside proxy-server.
After reinstalled squid everything works.
