### ISSUE TITLE
Error on pdagent

### ISSUE THREAD

**Issue by opistola** [PagerDuty/pdagent#154]
Hi, I have installed the pdagent on ubuntu 18.04.04 LTS, integrated with Nagios core and checked that it can send events to pagerduty. Still, when the notify cmd is executed by nagios i am getting this errors:

```2020-07-31 14:02:59,730 WARNING HeartbeatTask        pdagent.heartbeat    Error reading heartbeat response data:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdagent/heartbeat.py", line 147, in _process_response
    result = json.loads(response_str)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

2020-07-31 15:02:59,728 WARNING HeartbeatTask        pdagent.heartbeat    Error reading heartbeat response data:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdagent/heartbeat.py", line 147, in _process_response
    result = json.loads(response_str)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

2020-07-31 16:02:59,731 WARNING HeartbeatTask        pdagent.heartbeat    Error reading heartbeat response data:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdagent/heartbeat.py", line 147, in _process_response
    result = json.loads(response_str)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

2020-07-31 16:55:50,559 INFO    SendEventTask        pdagent.pdqueue      Processing event 1596214541429434_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt

2020-07-31 16:55:51,144 WARNING SendEventTask        pdagent.sendevent    Error reading response data while sending event:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdagent/sendevent.py", line 133, in send_event
    result = json.loads(result_str)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

2020-07-31 16:55:51,145 ERROR   SendEventTask        pdagent.sendevent    Error sending event 1596214541429434_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt; Error code: 200, Reason: b'{"status":"success","message":"Event processed","incident_key":"server.fire"}'

2020-07-31 16:55:51,145 INFO    SendEventTask        pdagent.pdqueue      Changing 1596214541429434_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt type: pdq -> suc...

2020-07-31 17:02:59,731 WARNING HeartbeatTask        pdagent.heartbeat    Error reading heartbeat response data:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdagent/heartbeat.py", line 147, in _process_response
    result = json.loads(response_str)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
How can i fix this?

Thanks in advance

**Comment by blagh** [comment]
Hi there, this looks like a bug, related to changes in how Python 3 deals with string vs bytes. I can't give you a specific timeline on a patch, but we're looking into it.

**Comment by blagh** [comment]
Hey there, we're working on patching a number of issues with the Python 3 pdagent in [this pull request][1]. It hasn't been released yet because we're still working on a few issues with it, but you can keep an eye on it in the meanwhile.

  [1]: https://github.com/PagerDuty/pdagent/pull/153/files#diff-80cce0530dcd66e7ec57b4e8868ff33dR137

**Comment by DolevAlgam** [comment]
Any updateon the PR? @blagh

**Comment by rlanyi** [comment]
for a quick fix:

1. `systemctl stop pdagent`

2. In `/usr/share/pdagent/bin/pdagentd` after the `then`, replace `python3` with `python` so it becomes:

```
if [ -x "$(command -v python3)" ];
then
    python $DIR/pdagentd.py "$@"
else
    python $DIR/pdagentd.py "$@"
fi
```

Note: double check if `python --version` gives Python 2 for you. If it doesn't, then update the command above accordingly.

3. `systemctl start pdagent`
