### ISSUE TITLE
ImportError: No module named pdagent.config : on RedHat 6.9

### ISSUE THREAD

**Issue by mayankgupta0510** [PagerDuty/pdagent#159]
[root@mo-0bda67593 bin]# pd-send -k cf2b1fbcc57646fdb1b6f3cc6f0564d0 -t trigger -d "Test test" -i server.test
Traceback (most recent call last):
  File "/usr/bin/pd-send.py", line 126, in <module>
    import pdagent.config
ImportError: No module named pdagent.config

**Comment by arlinux** [comment]
Perform the following procedure:

For example: use your new python ver and copy
# cp -a /usr/lib/python2.7/site-packages/pdagent /usr/share/pdagent/bin/

Then try restart!!

**Comment by tayarajat** [comment]
Post doing this there might even be the case that there is python3 on your system and pd-send is picking up that.
You can try any of these:

- python /usr/bin/pd-send.py  instead of pd-send 
- /usr/bin/pd-send file have an if condition to check python version. Remove that and use the else part only to use python2

**Comment by kerberos6** [comment]
hello,
i've a similar issue when try to run: pd-send --help

this is the output:

Traceback (most recent call last):
  File "/usr/bin/pd-send.py", line 120, in <module>
    import pdagent.config
ModuleNotFoundError: No module named 'pdagent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pd-send.py", line 126, in <module>
    import pdagent.config
ModuleNotFoundError: No module named 'pdagent'

i try both of this commands but not solved:

cp -a /usr/lib/python3.6/site-packages/pdagent /usr/share/pdagent/bin/
cp -a /usr/lib/python2.7/site-packages/pdagent /usr/share/pdagent/bin/

also try python instead of python3 

could i try check something else? 

thanks
