### ISSUE TITLE
Latest version of pdagent doesn't work with python3

### ISSUE THREAD

**Issue by bzlom** [PagerDuty/pdagent#169]
I'm running **Amazon Linux 2023** that comes preinstalled with python3 (**3.9.16**). I have created a symlink from python to python3:
```
[root@ip-10-7-3-153 bin]# which python3
/usr/bin/python3
[root@ip-10-7-3-153 bin]# which python
/usr/bin/python
[root@ip-10-7-3-153 bin]# ls -la /usr/bin/python
lrwxrwxrwx. 1 root root 16 Nov 27 13:08 /usr/bin/python -> /usr/bin/python3
```
I'm trying to start Pagerduty (**pdagent-1.7.3-1.noarch, pdagent-integrations-1.6.2-1.noarch**) but I'm getting the following errors:

```Nov 27 13:12:33 server.local systemd[1]: Starting pdagent.service - PagerDuty Agent...
Nov 27 13:12:33 server.local systemd[1]: Started pdagent.service - PagerDuty Agent.
Nov 27 13:12:33 server.local pdagentd[43558]: Traceback (most recent call last):
Nov 27 13:12:33 server.local pdagentd[43558]:   File "/usr/share/pdagent/bin/pdagentd.py", line 75, in <module>
Nov 27 13:12:33 server.local pdagentd[43558]:     import pdagent.config
Nov 27 13:12:33 server.local pdagentd[43558]: ModuleNotFoundError: No module named 'pdagent'
Nov 27 13:12:33 server.local pdagentd[43558]: During handling of the above exception, another exception occurred:
Nov 27 13:12:33 server.local pdagentd[43558]: Traceback (most recent call last):
Nov 27 13:12:33 server.local pdagentd[43558]:   File "/usr/share/pdagent/bin/pdagentd.py", line 81, in <module>
Nov 27 13:12:33 server.local pdagentd[43558]:     import pdagent.config
Nov 27 13:12:33 server.local pdagentd[43558]: ModuleNotFoundError: No module named 'pdagent'
Nov 27 13:12:33 server.local systemd[1]: pdagent.service: Main process exited, code=exited, status=1/FAILURE
Nov 27 13:12:33 server.local systemd[1]: pdagent.service: Failed with result 'exit-code'.
```

It works completely fine if I'm using its old **python2.x** libraries: 
`cp -a /usr/lib/python2.7/site-packages/pdagent/ /usr/share/pdagent/bin/pdagent/`

Does it run with python3? Or are there any plans to make it work with it?

**Comment by shivinder** [comment]
It says in the [README.md] file for this project - "PagerDuty is planning to deprecate this tool in favour of [go-pdagent](https://github.com/PagerDuty/go-pdagent). go-pdagent is not feature complete at this moment however it will be before an official deprecation notice."
This probably is an indication of what you said in your comments. It may not ever get Python3 support.

**Comment by lchopfpt** [comment]
Hello, are there any updates here?  It's feeling like pdagent and friends have been abandoned.

**Comment by dbray925** [comment]
Wait, so current agent is incompatible with the current supported version Python, and there is no fix for this, because they are focusing on a different language. Annoying! Thankfully, 3.6 seems to still work, so I just downgraded from 3.9 to 3.6:
```
sudo dnf -y remove python39
sudo alternatives --config python
```

**Comment by jdshewey** [comment]
While configuring an older version of Python is an option on Enterprise Linux 8, this option is not available on EL 9. This means that, at present Pager Duty cannot support the current version of python on the current version of Enterprise Linux. This is true as some vendors (like Nagios) and ending support for EL 8.

Meanwhile the go PD agent is still in beta and is not yet feature complete according to this documentation, with no patch for this bug in sight.

**Comment by hussainbani** [comment]
https://github.com/PagerDuty/pdagent/pull/181

Created this PR to fix this issue

You can get the new package for rocky8 with python3 issue solved on this link
